listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
realm=akirah
user=akirah:temporary
external-ip=$(detect-external-ip)
min-port=49152
max-port=65535
no-cli
no-tlsv1
no-tlsv1_1
simple-log
